### ISSUE TITLE
Add Spanish Translation

### ISSUE THREAD

**Issue by ricardo-larosa** [Consensys/ethereum-developer-tools-list#118]

**Comment by ricardo-larosa** [comment]
I'd like to take this.

**Comment by pi0neerpat** [comment]
@ricardo-larosa I know its been a hot minute, but are you still up for this? What do you need to accomplish this? Are there any tools/tricks we can use to make your life easier?

**Comment by Rafellus** [comment]
@pi0neerpat I will pickup this task. I will start learning Solidity and Ethereum Dapps ecosystem, so it will fit perfectly. Also want to share this content with Spanish speakers around my community.

**Comment by pi0neerpat** [comment]
Done in #293
