### ISSUE TITLE
Add ERC1538 to the Upgradebility Section

### ISSUE THREAD

**Issue by mudgen** [ConsenSys/ethereum-developer-tools-list#178]
Can you add ERC1538 to the Upgradebility Section?

ERC1538 is here: https://github.com/ethereum/EIPs/issues/1538

**Comment by pi0neerpat** [comment]
Same comment as here https://github.com/ConsenSys/ethereum-developer-tools-list/issues/261. 

🧙‍♂️ May the proxy be with you.

**Comment by mudgen** [comment]
Thanks.   EIP-2535 replaces this standard so I'll leave it out.
