### ISSUE TITLE
Add contract standards?

### ISSUE THREAD

**Issue by lunaroyster** [ConsenSys/ethereum-developer-tools-list#23]
[ERC-20](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20.md): The standard for implementing fungible tokens. Used in ICOs and crowdfunding.

[ERC-721](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md): The standard for implementing non-fungible tokens (NFTs) used in DApps such as Cryptokitties.

[ERC-165](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-165.md): Detection of standard interfaces.

**Comment by pakaplace** [comment]
Could you add this as a PR? Maybe other Other>> Token Contracts
