### ISSUE TITLE
Add Abridged for Out of the box tools

### ISSUE THREAD

**Issue by OKDuncan** [ConsenSys/ethereum-developer-tools-list#231]
abridged.io has a location for the [docs](https://abridged.gitbook.io/docs/), the [github](https://github.com/netgum/archanova), and the [playground](https://playground.archanova.run/?activate=help).

This frameworks offers the lightest weight solution for account contracts providing access to social recovery, arbitrary key generation, off-chain tx system, a dev owned relayer, ENS compatibility, and a variety of Auth solutions.

**Comment by stephenjesus** [comment]
https://onlinedevtools.in

its useful for developers

**Comment by pi0neerpat** [comment]
@stephenjesus the pop-up ad on the site you posted makes me very hesitant to even consider it.

@OKDuncan make a PR and lets get it merged
