### ISSUE TITLE
FOAM Stack Component Tools

### ISSUE THREAD

**Issue by bgoblirsch** [ConsenSys/ethereum-developer-tools-list#26]
- [Cliquebait](https://github.com/f-o-a-m/cliquebait) is a compact and easy to use Docker image that spins up a single-node Proof of Authority blockchain with Geth. It also generates a few accounts and gives them ether, as well as unlocks them for use via Web3.
- [Chanterelle](https://github.com/f-o-a-m/chanterelle) is a purely functional smart contract manager that offers strong types, great error handling, and a purescript build tool so that if you want to use Purescript (highly recommended), your build tool is in the same language as your custom stack.
- The [Purescript Web3 Library](https://github.com/f-o-a-m/purescript-web3) allows for interacting with an Ethereum node using Purescript. It covers Web3 API endpoints for sending transactions, querying blockchain state and metadata, and monitoring events.
- The [Purescript Web3 Generator](https://github.com/f-o-a-m/purescript-web3-generator) generates a library of Purescript modules from Solidity ABIs in order to template transactions and event filters/watchers. If you are using Chanterelle, you get this for free.

**Comment by pakaplace** [comment]
Maybe an "example stack" by project/spoke section would be useful?

**Comment by bgoblirsch** [comment]
Here is one of our example stacks:
[https://github.com/f-o-a-m/parking-dao](https://github.com/f-o-a-m/parking-dao)

**Comment by pi0neerpat** [comment]
Closing for now. Please re-open if its still relevant
