### ISSUE TITLE
What category does Eth95 fit into?

### ISSUE THREAD

**Issue by adrianmcli** [ConsenSys/ethereum-developer-tools-list#260]
Context: https://github.com/adrianmcli/eth95

Creator of Eth95 here, I'm not sure what category it fits into because it does two things:

1. Watch your contract artifact directory and gives you a UI to interact with all your contract functions. For example:
    ```shell
    $ npm install -g eth95
    ```
    And then
    ```shell
    $ eth95 ./build/contracts
    ```
2. Gives you a UI for any Etherscan-verified contract. This is the DAI stablecoin contract for example:
    ```
    https://eth95.dev/?network=1&address=0x6b175474e89094c44da98b954eedeac495271d0f
    ```

**Comment by pi0neerpat** [comment]
@adrianmcli I think for Eth95 it should go in `Ethereum ABI (Application Binary Interface) tools`

While I was looking through things I noticed that things are getting lumped into the `frontend-ethereum-apis` section. But they don't all make sense (eg. create-react-app).  I opened a PR to fix that here https://github.com/ConsenSys/ethereum-developer-tools-list/pull/270

**Comment by pi0neerpat** [comment]
Please open a PR to add it to the list! ✌
