### ISSUE TITLE
Add the Diamond Standard to the list

### ISSUE THREAD

**Issue by mudgen** [ConsenSys/ethereum-developer-tools-list#261]
I think that the Diamond Standard should be added to the list.  It should be added to the Upgradeability section and to the contract standards section.

"A diamond is a set of contracts that can access the same storage variables and share the same Ethereum address."

The Diamond Standard is here: https://github.com/ethereum/EIPs/issues/2535

Here is an example of a tool (in Python) that helps manage diamonds: https://github.com/lampshade9909/DiamondSetter

Blog post about that tool: http://joeyzacherl.com/2018/10/volleyfire-liquidity-provider-for-decentralized-exchanges/

Here is a blog post about upgrading with the Diamond Standard: https://hiddentao.com/archives/2020/05/28/upgradeable-smart-contracts-using-diamond-standard

Here is another blog post that covers upgrading contracts with the Diamond Standard:
https://medium.com/coinmonks/summary-of-ethereum-upgradeable-smart-contract-r-d-part-2-2020-db141af915a0

**Comment by pi0neerpat** [comment]
![](https://media.giphy.com/media/qDPg6HNz2NfAk/giphy.gif)

Please pick one or two of these to add and make a PR!

**Comment by mudgen** [comment]
Yes sir!
