### ISSUE TITLE
Add Alchemy to Test blockchain networks

### ISSUE THREAD

**Issue by elanh** [ConsenSys/ethereum-developer-tools-list#264]
[Alchemy](https://alchemyapi.io/) is a node provider and supplies enhanced developer tools.

**Comment by pi0neerpat** [comment]
This looks great! Please open a PR with the changes and we can get it added to the list.

**Comment by pi0neerpat** [comment]
Also, it appears like we need a new category for Node providers. I see that Quiknode is lumped together here which doesn't make sense https://github.com/ConsenSys/ethereum-developer-tools-list#ethereum-clients
