### ISSUE TITLE
Update to EcosystemResources.md

### ISSUE THREAD

**Issue by oneworldcoder** [ConsenSys/ethereum-developer-tools-list#266]
Hello,

Under [Knowledge/Education](https://github.com/ConsenSys/ethereum-developer-tools-list/blob/master/EcosystemResources.md#knowledgeeducation) Chainshot building blocks is listed as free courses. However, their courses are paid. Can I update the changes?

**Comment by pi0neerpat** [comment]
@oneworldcoder  Sure, please open a PR with the changes. Also would be nice if you included links to demonstrate the switch to a paid-only model. The last time I checked there was a free component still that was very useful.
