### ISSUE TITLE
Add me as a maintainer

### ISSUE THREAD

**Issue by pi0neerpat** [ConsenSys/ethereum-developer-tools-list#268]
Please add me as a maintainer, and anyone else who wants to help. Thank you!

**Comment by samajammin** [comment]
@pi0neerpat if you're interested in improving Ethereum dev documentation, we'd love your help on ethereum.org 😎 !

Docs: https://ethereum.org/en/developers/docs/
Github: https://github.com/ethereum/ethereum-org-website

Not to say that this repo _shouldn't be_ maintained but ethereum.org does have an active team behind it. Might make sense to consolidate efforts here & reduce the overall overhead for the community to maintain multiple resources.

Let me know what you think either way.

**Comment by pi0neerpat** [comment]
Thank you @ggg5053 !
