### ISSUE TITLE
Add testing for broken links

### ISSUE THREAD

**Issue by Rafellus** [Consensys/ethereum-developer-tools-list#294]
While making the translation for Spanish I found a broken link: [Parity Demo-PoA Tutorial](https://openethereum.github.io/wiki/Demo-PoA-tutorial.html). I leave the link in the translation as the task wasn't about changing stuff. But we could use a Github Action to check for broken links on push to master.

**Comment by pi0neerpat** [comment]
I think thats a great idea. Is there some existing solution you had in mind?

**Comment by Rafellus** [comment]
I check some and after a check to the code, this is a great and simple option: https://github.com/lycheeverse/lychee-action. I'm testing the workflow in my fork, to send a pull request today, with all the config.

**Comment by Rafellus** [comment]
Found one that works. This: https://github.com/marketplace/actions/markup-link-checker-mlc

I ran Github Actions in my fork and got great results: https://github.com/Rafellus/ethereum-developer-tools-list/runs/2748708518?check_suite_focus=true. You can find there the workflow YAML file.

Also adding this will be a good opportunity for adding a [status badge](https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge).

**Comment by sirhashalot** [comment]
This was fixed by PR #314
