### ISSUE TITLE
[Alethio](https://aleth.io/) Link Broken or website Down!

### ISSUE THREAD

**Issue by BigGangy** [ConsenSys/ethereum-developer-tools-list#328]
[Alethio](https://aleth.io/) -
An advanced Ethereum analytics platform that provides live monitoring, insights and anomaly detection, token metrics, smart contract audits, graph visualization, and blockchain search. Real-time market information and trading activities across Ethereum's decentralized exchanges can also be explored.

**Comment by pi0neerpat** [comment]
I recommend contacting the project maintainers at Alethio to solve this one.
