### ISSUE TITLE
Decentralized Exchanges, a comprehensive list.

### ISSUE THREAD

**Issue by eliooses** [ConsenSys/ethereum-developer-tools-list#34]
Hi there @pakaplace !

I have been working since last year on this list of decentralized exchanges called inDEX:
https://github.com/distribuyed/index

Please let me know what you think is the right way to contribute with the section that I see in this great list that you have created.

Best regards from Buenos Aires.

**Comment by pakaplace** [comment]
Thanks @eliooses, maybe we should just put the lin in the list ~meta~  Not really a dev tool, but nonetheless good to know.
