### ISSUE TITLE
DappHub tools

### ISSUE THREAD

**Issue by seanwbren** [ConsenSys/ethereum-developer-tools-list#35]
DappHub created a suite of command line tools:

https://dapp.tools/dapp/ -- Build, test, deploy and transact with Ethereum contracts from the comfort of the command-line.

https://dapp.tools/seth/ -- Slice and dice transactions, query the blockchain, convert between data formats, perform remote calls, estimate gas usage and more.

https://dapp.tools/hevm/ -- An EVM for testing and verification, with a nimble debugger that runs in the terminal.

Also, OasisDex at oasisdex.com and OasisDirect at oasis.direct are decentralized exchanges.

**Comment by pi0neerpat** [comment]
@seanwbren these look awesome! Please open a PR with the changes and we can get them added to the list.
