### ISSUE TITLE
Ethereum wallet me

### ISSUE THREAD

**Issue by Rodry654** [Consensys/ethereum-developer-tools-list#440]

**Comment by Rodry654** [comment]
![IMG_20240921_052319_465](https://github.com/user-attachments/assets/b7b90c8b-73f8-4c7e-89ac-8c6fe3066e15)
![IMG_20240924_050328_258](https://github.com/user-attachments/assets/f25bfe93-c7f7-41d0-8190-0d68431ae93a)
![IMG_20240921_052319_465](https://github.com/user-attachments/assets/00ec46ac-8498-42ce-98a2-4fbefc1162dc)
![Screenshot_20240924-013618](https://github.com/user-attachments/assets/2fa6ebac-1b34-4a6c-bb73-2d4163cb98a1)

**Comment by pi0neerpat** [comment]
idk what this is
